local util = require("ultraviolet.util")
local M = {}

--- @param t ultraviolet.Palette
function M.get(t)
    return {
        ["@annotation"]                         = { link = "PreProc" },
        ["@attribute"]                          = { fg = t.lilac },
        ["@boolean"]                            = { link = "Boolean" },
        ["@character"]                          = { link = "Character" },
        ["@character.special"]                  = { link = "SpecialChar" },
        ["@comment"]                            = { link = "Comment" },
        ["@comment.documentation"]              = { fg = t.muted, italic = true },
        ["@conditional"]                        = { link = "Conditional" },
        ["@constant"]                           = { link = "Constant" },
        ["@constant.builtin"]                   = { fg = t.pink },
        ["@constant.macro"]                     = { link = "Define" },
        ["@constructor"]                        = { fg = t.violet },
        ["@debug"]                              = { link = "Debug" },
        ["@define"]                             = { link = "Define" },
        ["@exception"]                          = { link = "Exception" },
        ["@field"]                              = { fg = t.lavender },
        ["@float"]                              = { link = "Float" },
        ["@function"]                           = { link = "Function" },
        ["@function.builtin"]                   = { fg = t.pink },
        ["@function.call"]                      = { link = "@function" },
        ["@function.macro"]                     = { link = "Macro" },
        ["@function.method"]                    = { fg = t.violet },
        ["@function.method.call"]               = { fg = t.violet },
        ["@include"]                            = { link = "Include" },
        ["@keyword"]                            = { link = "Keyword" },
        ["@keyword.coroutine"]                  = { link = "@keyword" },
        ["@keyword.function"]                   = { link = "Keyword" },
        ["@keyword.operator"]                   = { link = "Operator" },
        ["@keyword.return"]                     = { link = "@keyword" },
        ["@keyword.type"]                       = { fg = t.purple, italic = true },
        ["@label"]                              = { link = "Label" },
        ["@module"]                             = { fg = t.fg },
        ["@namespace"]                          = { fg = t.fg },
        ["@none"]                               = { default = true },
        ["@number"]                             = { link = "Number" },
        ["@number.float"]                       = { link = "Float" },
        ["@operator"]                           = { link = "Operator" },
        ["@parameter"]                          = { fg = t.fg },
        ["@preproc"]                            = { link = "PreProc" },
        ["@property"]                           = { fg = t.lavender },
        ["@punctuation.bracket"]                = { fg = t.fg },
        ["@punctuation.delimiter"]              = { fg = t.fg },
        ["@punctuation.special"]                = { fg = t.rose },
        ["@repeat"]                             = { link = "Repeat" },
        ["@storageclass"]                       = { link = "StorageClass" },
        ["@string"]                             = { link = "String" },
        ["@string.documentation"]               = { link = "Comment" },
        ["@string.escape"]                      = { fg = t.green },
        ["@string.regexp"]                      = { fg = t.green },
        ["@string.special"]                     = { link = "SpecialChar" },
        ["@symbol"]                             = { fg = t.lavender },
        ["@tag"]                                = { fg = t.purple },
        ["@tag.attribute"]                      = { fg = t.lavender },
        ["@tag.delimiter"]                      = { fg = t.fg },
        ["@type"]                               = { link = "Type" },
        ["@type.builtin"]                       = { fg = t.lilac },
        ["@type.definition"]                    = { link = "Typedef" },
        ["@type.qualifier"]                     = { link = "@keyword" },
        ["@variable"]                           = { fg = t.fg },
        ["@variable.builtin"]                   = { fg = t.pink },
        ["@variable.member"]                    = { fg = t.lavender },
        ["@variable.parameter"]                 = { fg = t.fg },

        -- Markup
        ["@markup.heading.1"]                   = { link = "markdownH1" },
        ["@markup.heading.2"]                   = { link = "markdownH2" },
        ["@markup.heading.3"]                   = { link = "markdownH3" },
        ["@markup.heading.4"]                   = { link = "markdownH4" },
        ["@markup.heading.5"]                   = { link = "markdownH5" },
        ["@markup.heading.6"]                   = { link = "markdownH6" },
        ["@markup.italic"]                      = { italic = true },
        ["@markup.strong"]                      = { bold = true },
        ["@markup.link"]                        = { fg = t.blue, underline = true },
        ["@markup.link.label"]                  = { fg = t.blue },
        ["@markup.link.url"]                    = { fg = t.blue, underline = true },
        ["@markup.list"]                        = { fg = t.purple },
        ["@markup.list.checked"]                = { fg = t.green, bold = true },
        ["@markup.list.unchecked"]              = { fg = t.lilac, bold = true },
        ["@markup.quote"]                       = { link = "Comment" },
        ["@markup.raw"]                         = { fg = t.teal },
        ["@markup.raw.block"]                   = { fg = t.teal },
        ["@markup.strikethrough"]               = { strikethrough = true },
        ["@markup.underline"]                   = { underline = true },

        -- Rust-specific (bonus)
        ["@lsp.type.namespace.rust"]            = { fg = t.fg },
        ["@lsp.type.macro.rust"]                = { fg = t.rose },
        ["@lsp.type.builtinType.rust"]          = { fg = t.lilac },
        ["@lsp.type.typeParameter.rust"]        = { fg = t.lavender },
        ["@lsp.type.lifetime.rust"]             = { fg = t.pink, italic = true },
    }
end

return M
